PVDS/config/routes.rb
Rails.application.routes.draw do
  resources :estudiantes
  resources :poblacions
  resources :cursos
  resources :administradors
  resources :puntos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

PVDS/app/models/administrador.rb
class Administrador < ApplicationRecord
  belongs_to :puntos
end

PVDS/app/controllers/administradors_controller.rb
class AdministradorsController < ApplicationController
  before_action :set_administrador, only: [:show, :edit, :update, :destroy]

  # GET /administradors
  # GET /administradors.json
  def index
    @administradors = Administrador.all
  end

  # GET /administradors/1
  # GET /administradors/1.json
  def show
  end

  # GET /administradors/new
  def new
    @administrador = Administrador.new
  end

  # GET /administradors/1/edit
  def edit
  end

  # POST /administradors
  # POST /administradors.json
  def create
    @administrador = Administrador.new(administrador_params)

    respond_to do |format|
      if @administrador.save
        format.html { redirect_to @administrador, notice: 'Administrador was successfully created.' }
        format.json { render :show, status: :created, location: @administrador }
      else
        format.html { render :new }
        format.json { render json: @administrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administradors/1
  # PATCH/PUT /administradors/1.json
  def update
    respond_to do |format|
      if @administrador.update(administrador_params)
        format.html { redirect_to @administrador, notice: 'Administrador was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrador }
      else
        format.html { render :edit }
        format.json { render json: @administrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administradors/1
  # DELETE /administradors/1.json
  def destroy
    @administrador.destroy
    respond_to do |format|
      format.html { redirect_to administradors_url, notice: 'Administrador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrador
      @administrador = Administrador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrador_params
      params.require(:administrador).permit(:nombre, :cedula, :puntos_id)
    end
end

PVDS/app/helpers/administradors_helper.rb
module AdministradorsHelper
end

PVDS/app/views/administradors/_form.html.erb
<%= form_with(model: administrador, local: true) do |form| %>
  <% if administrador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(administrador.errors.count, "error") %> prohibited this administrador from being saved:</h2>

      <ul>
      <% administrador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :cedula %>
    <%= form.number_field :cedula %>
  </div>

  <div class="field">
    <%= form.label :puntos_id %>
    <%= form.text_field :puntos_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

PVDS/app/views/administradors/edit.html.erb
<h1>Editing Administrador</h1>

<%= render 'form', administrador: @administrador %>

<%= link_to 'Show', @administrador %> |
<%= link_to 'Back', administradors_path %>

PVDS/app/views/administradors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Administradors</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Cedula</th>
      <th>Puntos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @administradors.each do |administrador| %>
      <tr>
        <td><%= administrador.nombre %></td>
        <td><%= administrador.cedula %></td>
        <td><%= administrador.puntos %></td>
        <td><%= link_to 'Show', administrador %></td>
        <td><%= link_to 'Edit', edit_administrador_path(administrador) %></td>
        <td><%= link_to 'Destroy', administrador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Administrador', new_administrador_path %>

PVDS/app/views/administradors/new.html.erb
<h1>New Administrador</h1>

<%= render 'form', administrador: @administrador %>

<%= link_to 'Back', administradors_path %>

PVDS/app/views/administradors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @administrador.nombre %>
</p>

<p>
  <strong>Cedula:</strong>
  <%= @administrador.cedula %>
</p>

<p>
  <strong>Puntos:</strong>
  <%= @administrador.puntos %>
</p>

<%= link_to 'Edit', edit_administrador_path(@administrador) %> |
<%= link_to 'Back', administradors_path %>