rails/PVDS/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root"home#index"
  resources :users
  resources :poblations
  resources :courses
  resources :points
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails/PVDS/app/models/poblation.rb
class Poblation < ApplicationRecord
end

rails/PVDS/app/controllers/poblations_controller.rb
class PoblationsController < ApplicationController
  before_action :set_poblation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /poblations
  # GET /poblations.json
  def index
    @poblations = Poblation.all
  end

  # GET /poblations/1
  # GET /poblations/1.json
  def show
  end

  # GET /poblations/new
  def new
    @poblation = Poblation.new
  end

  # GET /poblations/1/edit
  def edit
  end

  # POST /poblations
  # POST /poblations.json
  def create
    @poblation = Poblation.new(poblation_params)

    respond_to do |format|
      if @poblation.save
        format.html { redirect_to @poblation, notice: 'Poblation was successfully created.' }
        format.json { render :show, status: :created, location: @poblation }
      else
        format.html { render :new }
        format.json { render json: @poblation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poblations/1
  # PATCH/PUT /poblations/1.json
  def update
    respond_to do |format|
      if @poblation.update(poblation_params)
        format.html { redirect_to @poblation, notice: 'Poblation was successfully updated.' }
        format.json { render :show, status: :ok, location: @poblation }
      else
        format.html { render :edit }
        format.json { render json: @poblation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poblations/1
  # DELETE /poblations/1.json
  def destroy
    @poblation.destroy
    respond_to do |format|
      format.html { redirect_to poblations_url, notice: 'Poblation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poblation
      @poblation = Poblation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poblation_params
      params.require(:poblation).permit(:nombre)
    end
end

rails/PVDS/app/helpers/poblations_helper.rb
module PoblationsHelper
end

rails/PVDS/app/views/poblations/_form.html.erb
<%= form_with(model: poblation, local: true) do |form| %>
  <% if poblation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poblation.errors.count, "error") %> prohibited this poblation from being saved:</h2>

      <ul>
      <% poblation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails/PVDS/app/views/poblations/edit.html.erb
<h1>Editing Poblation</h1>

<%= render 'form', poblation: @poblation %>

<%= link_to 'Show', @poblation %> |
<%= link_to 'Back', poblations_path %>

rails/PVDS/app/views/poblations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Poblations</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @poblations.each do |poblation| %>
      <tr>
        <td><%= poblation.nombre %></td>
        <td><%= link_to 'Show', poblation %></td>
        <td><%= link_to 'Edit', edit_poblation_path(poblation) %></td>
        <td><%= link_to 'Destroy', poblation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poblation', new_poblation_path %>

rails/PVDS/app/views/poblations/new.html.erb
<h1>New Poblation</h1>

<%= render 'form', poblation: @poblation %>

<%= link_to 'Back', poblations_path %>

rails/PVDS/app/views/poblations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @poblation.nombre %>
</p>

<%= link_to 'Edit', edit_poblation_path(@poblation) %> |
<%= link_to 'Back', poblations_path %>